# Generated by Django 3.2.12 on 2022-04-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_weight_patient_mass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
