# Generated by Django 3.2.12 on 2022-04-02 20:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_temperature', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('relative_humidity', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('air_pollution', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('body_temperature', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('systolic_blood_pressure', models.IntegerField(null=True)),
                ('diastolic_blood_pressure', models.IntegerField(null=True)),
                ('oxygen_saturation', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('heart_rate', models.IntegerField(null=True)),
                ('ecg', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 4, 2, 20, 44, 27, 325985, tzinfo=utc))),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
