version: "3.9"

services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/app
    ports:
        - 8000:8000
    env_file:
        - .env
    restart: "on-failure"
    depends_on:
        - mysql-db
    networks:
        - core
  mysql-db:
    image: mariadb:10.5
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - core
    environment:
      - MYSQL_DATABASE=${MYSQL_DBNAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    ports:
      - 3306:3306


networks:
   core:
      driver: bridge

volumes:
   db_data: null